#!/usr/bin/env bash

KERNEL_NAME="QuartiX"
GKI_VERSION="android12-5.10"
USER="eraselk"
HOST="gacorprjkt"
TIMEZONE="Asia/Makassar"
ANYKERNEL_REPO="https://github.com/linastorvaldz/anykernel"
ANYKERNEL_BRANCH="gki"
KERNEL_REPO="https://github.com/linastorvaldz/kernel_new"
KERNEL_BRANCH="android12-5.10"
KERNEL_DEFCONFIG="gki_defconfig"
DEFCONFIGS_TO_MERGE=""
GKI_RELEASES_REPO="https://github.com/linastorvaldz/quartix-releases"
CLANG_URL="$(./clang.sh slim)"
ZIP_NAME="$KERNEL_NAME-KVER-VARIANT.zip"
